# Generated by Django 5.0 on 2025-11-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Property Title')),
                ('code', models.CharField(help_text='Unique identifier for property', max_length=50, unique=True, verbose_name='Property Code')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area (m²)')),
                ('bedrooms', models.IntegerField(default=0, verbose_name='Bedrooms')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='Bathrooms')),
                ('floors', models.IntegerField(default=1, verbose_name='Floors')),
                ('parking_spaces', models.IntegerField(default=0, verbose_name='Parking Spaces')),
                ('year_built', models.IntegerField(blank=True, null=True, verbose_name='Year Built')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Price')),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Market Value')),
                ('rental_price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Rental Price')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='Has Elevator')),
                ('has_garden', models.BooleanField(default=False, verbose_name='Has Garden')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Has Swimming Pool')),
                ('has_security', models.BooleanField(default=False, verbose_name='Has Security')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Furnished')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Under Maintenance'), ('sold', 'Sold')], default='available', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='owners.owner', verbose_name='Owner')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype', verbose_name='Property Type')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('deed', 'Property Deed'), ('contract', 'Contract'), ('insurance', 'Insurance'), ('inspection', 'Inspection Report'), ('permit', 'Permit'), ('other', 'Other')], max_length=20, verbose_name='Document Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('file', models.FileField(upload_to='properties/documents/%Y/%m/', verbose_name='File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Image')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['code'], name='properties__code_695bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_74fa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active'], name='properties__is_acti_78cc81_idx'),
        ),
    ]
