# Generated by Django 5.0 on 2025-11-05 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='average_roi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average return on investment percentage', max_digits=5, null=True, verbose_name='Average ROI'),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_rating',
            field=models.CharField(blank=True, max_length=10, verbose_name='Energy Rating'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Floor Number'),
        ),
        migrations.AddField(
            model_name='property',
            name='last_renovation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Renovation Date'),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Occupancy percentage (0-100)', max_digits=5, null=True, verbose_name='Occupancy Rate'),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Pets Allowed'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Floors'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, verbose_name='Virtual Tour URL'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('security', 'Security'), ('technology', 'Technology'), ('other', 'Other')], default='other', max_length=20, verbose_name='Amenity Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Amenity',
                'verbose_name_plural': 'Property Amenities',
                'ordering': ['amenity_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('expense_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('tax', 'Tax'), ('insurance', 'Insurance'), ('management', 'Management'), ('other', 'Other')], default='other', max_length=20, verbose_name='Expense Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('vendor', models.CharField(blank=True, max_length=200, verbose_name='Vendor')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='properties/expenses/%Y/%m/', verbose_name='Receipt')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recurring')),
                ('recurrence_frequency', models.CharField(choices=[('once', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='once', max_length=20, verbose_name='Recurrence Frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Expense',
                'verbose_name_plural': 'Property Expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Inspection Date')),
                ('inspector_name', models.CharField(max_length=200, verbose_name='Inspector Name')),
                ('inspection_type', models.CharField(choices=[('routine', 'Routine'), ('safety', 'Safety'), ('pre_purchase', 'Pre-purchase'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='routine', max_length=20, verbose_name='Inspection Type')),
                ('overall_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20, verbose_name='Overall Condition')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommendations')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Next Inspection Date')),
                ('document', models.FileField(blank=True, null=True, upload_to='properties/inspections/%Y/%m/', verbose_name='Inspection Report')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Inspection',
                'verbose_name_plural': 'Property Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_date', models.DateField(verbose_name='Revenue Date')),
                ('revenue_type', models.CharField(choices=[('rent', 'Rent'), ('service', 'Service Charge'), ('parking', 'Parking'), ('other', 'Other')], default='rent', max_length=20, verbose_name='Revenue Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_revenues', to='contracts.contract', verbose_name='Contract')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Revenue',
                'verbose_name_plural': 'Property Revenues',
                'ordering': ['-revenue_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(verbose_name='Valuation Date')),
                ('valuation_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valuation Amount')),
                ('valuation_type', models.CharField(choices=[('market', 'Market Valuation'), ('bank', 'Bank Valuation'), ('insurance', 'Insurance Valuation'), ('other', 'Other')], default='market', max_length=20, verbose_name='Valuation Type')),
                ('valuator_name', models.CharField(blank=True, max_length=200, verbose_name='Valuator Name')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('document', models.FileField(blank=True, null=True, upload_to='properties/valuations/%Y/%m/', verbose_name='Valuation Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Valuation',
                'verbose_name_plural': 'Property Valuations',
                'ordering': ['-valuation_date'],
            },
        ),
    ]
