# Generated by Django 5.0 on 2025-11-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_average_roi_property_energy_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='For Sale'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Property sale price', max_digits=15, null=True, verbose_name='Sale Price'),
        ),
    ]
