# Generated by Django 5.0 on 2025-11-06 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='owner',
            name='mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='owner',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax ID'),
        ),
    ]
